# Generated by Django 2.2.1 on 2019-05-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version1_0', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='job',
            field=models.TextField(default=''),
        ),
    ]
