# Generated by Django 2.2.1 on 2019-05-28 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version1_0', '0002_auto_20190516_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='BeverageId',
            field=models.TextField(
                default='NNN', max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='Category',
            field=models.ForeignKey(default='CX', on_delete=django.db.models.deletion.SET_DEFAULT,
                                    related_name='products', to='version1_0.Category'),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='Shop',
            field=models.ForeignKey(default='X', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='beverages', to='version1_0.Shop'),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='imagePath',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='info',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='remark',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AlterField(
            model_name='beveragesize',
            name='BeverageId',
            field=models.ForeignKey(default='XXX', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='sizes', to='version1_0.Beverage'),
        ),
        migrations.AlterField(
            model_name='beveragesize',
            name='Number',
            field=models.IntegerField(
                default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='imagePath',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='info',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logoPath',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='remark',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='info',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='job',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photoPath',
            field=models.TextField(default='none', null=True),
        ),
    ]
