# Generated by Django 2.2.1 on 2019-05-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version1_0', '0004_auto_20190528_2120'),
    ]

    # operations = [
    #    migrations.RenameField(
    #        model_name='teammember',
    #        old_name='info',
    #        new_name='introduction',
    #    ),
    # ]
