# Generated by Django 2.2.1 on 2019-05-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version1_0', '0005_auto_20190528_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeverageCapacity',
            fields=[
                ('Number', models.IntegerField(
                    default=0, primary_key=True, serialize=False)),
                ('capacity', models.TextField(default='M', max_length=2)),
                ('price', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('BeverageId', models.ForeignKey(default='XXX', on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='capacitys', to='version1_0.Beverage')),
            ],
        ),
        migrations.DeleteModel(
            name='BeverageSize',
        ),
    ]
