# Generated by Django 2.2.1 on 2019-06-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version1_0', '0006_auto_20190530_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='info',
            new_name='introduction',
        ),
    ]
